### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by ZakTaccardi** [graphcool/cuid-java#1]
```
E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
                                                                                       at cool.graph.cuid.Cuid.getHostInfo(Cuid.java:24)
                                                                                       at cool.graph.cuid.Cuid.getFingerprint(Cuid.java:34)
                                                                                       at cool.graph.cuid.Cuid.<clinit>(Cuid.java:18)
```

**Comment by marktani** [comment]
Thanks for the report, I will have a look next week.

**Comment by marktani** [comment]
`ManagementFactory` is not a part of the VM Android is running on, but a part of the regular JVM. Right now, I don't see a good way to support both vanilla Java and Android in the same library. Maybe you got an idea? Feel free to create a PR if you've come up with a solution.

**Comment by atoji** [comment]
What do you think using the default host when receive a NoClassDefFoundError exception?
